# Generated by Django 5.0.6 on 2024-05-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
