# Generated by Django 5.0.6 on 2024-05-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_booking_booking_date_booking_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='house',
        ),
    ]
